version: '3'

services:
  odoo:
    image: odoo:19.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=strongpassword
    volumes:
      - ./addons:/mnt/extra-addons
      - odoo-data:/var/lib/odoo

  db:
    image: postgres:18
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=strongpassword
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql

volumes:
  odoo-data:
  postgres-data:
